version: '3'

services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    command: yarn dev
    ports:
      - "8080:8080"
    volumes:  
      - .:/usr/src/app
      - /usr/src/app/node_modules
