FROM node:10.4-alpine
# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./
COPY webpack.config.js ./
COPY .babelrc ./

RUN yarn install

# Bundle app source
COPY index.html ./
COPY ./project/frontend/src ./project/frontend/src

EXPOSE 8080
